addListing page from clone project
hthm00/biz-everywhere pull request #11
Opened 2023-02-18 02:14 UTC by trampham1104

2023-02-18 04:40 UTC, hthm00 requested changes
The file is empty!

2023-02-19 01:43 UTC, trampham1104 commented
> The file is empty!

> Just update it, can you check again? Thank you 🤓

2023-02-19 02:52 UTC, hthm00 commented on pages/createListing.html
> +      <button type="draft" class="btn btn-secondary">Save Draft</button>
There is no type "draft" in a button tag.

2023-02-19 03:00 UTC, hthm00 requested changes
Overall, good work!

2023-02-19 03:00 UTC, hthm00 commented on pages/createListing.html
> +
Missing a form

2023-02-19 03:00 UTC, hthm00 commented on pages/createListing.html
> +      <div class="enterinfo">
Class name is incorrect.

2023-02-19 03:00 UTC, hthm00 commented on pages/createListing.html
> +          <span class="input-group-text" id="addon-wrapping">Enter your anana Name</span>
id field is not descriptive

2023-03-31 23:14 UTC, closed without merging